'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Masterchest_Wallet.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADDITIONAL INFORMATION:.
        '''</summary>
        Friend ReadOnly Property additionalinformation() As String
            Get
                Return ResourceManager.GetString("additionalinformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Alpha.
        '''</summary>
        Friend ReadOnly Property addressalpha() As String
            Get
                Return ResourceManager.GetString("addressalpha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Addresslist exception.
        '''</summary>
        Friend ReadOnly Property addresslistexception() As String
            Get
                Return ResourceManager.GetString("addresslistexception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available:.
        '''</summary>
        Friend ReadOnly Property available() As String
            Get
                Return ResourceManager.GetString("available", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to addresses.
        '''</summary>
        Friend ReadOnly Property baddresses() As String
            Get
                Return ResourceManager.GetString("baddresses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BTC Balance.
        '''</summary>
        Friend ReadOnly Property balancebtc() As String
            Get
                Return ResourceManager.GetString("balancebtc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSC Balance.
        '''</summary>
        Friend ReadOnly Property balancemsc() As String
            Get
                Return ResourceManager.GetString("balancemsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to contracts.
        '''</summary>
        Friend ReadOnly Property bcontracts() As String
            Get
                Return ResourceManager.GetString("bcontracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to currencies.
        '''</summary>
        Friend ReadOnly Property bcurrencies() As String
            Get
                Return ResourceManager.GetString("bcurrencies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to debug.
        '''</summary>
        Friend ReadOnly Property bdebug() As String
            Get
                Return ResourceManager.GetString("bdebug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to exchange.
        '''</summary>
        Friend ReadOnly Property bexchange() As String
            Get
                Return ResourceManager.GetString("bexchange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FINISH.
        '''</summary>
        Friend ReadOnly Property bfinish() As String
            Get
                Return ResourceManager.GetString("bfinish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to history.
        '''</summary>
        Friend ReadOnly Property bhistory() As String
            Get
                Return ResourceManager.GetString("bhistory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to blocks to catch up.
        '''</summary>
        Friend ReadOnly Property blockscatchup() As String
            Get
                Return ResourceManager.GetString("blockscatchup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to overview.
        '''</summary>
        Friend ReadOnly Property boverview() As String
            Get
                Return ResourceManager.GetString("boverview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to send.
        '''</summary>
        Friend ReadOnly Property bsend() As String
            Get
                Return ResourceManager.GetString("bsend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property bsendnew() As String
            Get
                Return ResourceManager.GetString("bsendnew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend ReadOnly Property bsignsend() As String
            Get
                Return ResourceManager.GetString("bsignsend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitcoin sends are temporarily disabled in this build..
        '''</summary>
        Friend ReadOnly Property btcsenddisabled() As String
            Get
                Return ResourceManager.GetString("btcsenddisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEST.
        '''</summary>
        Friend ReadOnly Property btest() As String
            Get
                Return ResourceManager.GetString("btest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Settings.
        '''</summary>
        Friend ReadOnly Property bupdatesettings() As String
            Get
                Return ResourceManager.GetString("bupdatesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Sanity checking balances table...&quot;.
        '''</summary>
        Friend ReadOnly Property cerror() As String
            Get
                Return ResourceManager.GetString("cerror", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SHOW SCROLLBARS.
        '''</summary>
        Friend ReadOnly Property checkdebugscroll() As String
            Get
                Return ResourceManager.GetString("checkdebugscroll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use a preseeded database.
        '''</summary>
        Friend ReadOnly Property chkpreseed() As String
            Get
                Return ResourceManager.GetString("chkpreseed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property closeicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closeicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please Complete All Fields..
        '''</summary>
        Friend ReadOnly Property completeFields() As String
            Get
                Return ResourceManager.GetString("completeFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration file error.
        '''</summary>
        Friend ReadOnly Property configFileError() As String
            Get
                Return ResourceManager.GetString("configFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to copy.
        '''</summary>
        Friend ReadOnly Property copypar() As String
            Get
                Return ResourceManager.GetString("copypar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currencylist exception.
        '''</summary>
        Friend ReadOnly Property currencylistexception() As String
            Get
                Return ResourceManager.GetString("currencylistexception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Block:.
        '''</summary>
        Friend ReadOnly Property currentblock() As String
            Get
                Return ResourceManager.GetString("currentblock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Block Analysis for:.
        '''</summary>
        Friend ReadOnly Property debugblockanalysis() As String
            Get
                Return ResourceManager.GetString("debugblockanalysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DISCLAIMER:.
        '''</summary>
        Friend ReadOnly Property disclaimer1() As String
            Get
                Return ResourceManager.GetString("disclaimer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This software is pre-release software for testing only..
        '''</summary>
        Friend ReadOnly Property disclaimer2() As String
            Get
                Return ResourceManager.GetString("disclaimer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The protocol and transaction processing rules for Mastercoin are still under active development and are subject to change in future..
        '''</summary>
        Friend ReadOnly Property disclaimer3() As String
            Get
                Return ResourceManager.GetString("disclaimer3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO NOT USE IT WITH A LARGE AMOUNT OF MASTERCOINS AND/OR BITCOINS.  IT IS ENTIRELY POSSIBLE YOU MAY LOSE ALL YOUR COINS.  INFORMATION DISPLAYED MAY BE INCORRECT.  MASTERCHEST OFFERS ABSOLUTELY NO GUARANTEES OF ANY KIND.
        '''</summary>
        Friend ReadOnly Property disclaimer4() As String
            Get
                Return ResourceManager.GetString("disclaimer4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A fraction of a bitcoin and a fraction of a mastercoin are the suggested testing amounts.  Preferably use a fresh bitcoin wallet.dat..
        '''</summary>
        Friend ReadOnly Property disclaimer5() As String
            Get
                Return ResourceManager.GetString("disclaimer5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This software is provided open-source at no cost.  You are responsible for knowing the law in your country and determining if your use of this software contravenes any local laws..
        '''</summary>
        Friend ReadOnly Property disclaimer6() As String
            Get
                Return ResourceManager.GetString("disclaimer6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Empty Balances.
        '''</summary>
        Friend ReadOnly Property emptybalances() As String
            Get
                Return ResourceManager.GetString("emptybalances", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw transaction is empty - stopping..
        '''</summary>
        Friend ReadOnly Property emptyrawtx() As String
            Get
                Return ResourceManager.GetString("emptyrawtx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to enter your bitcoin wallet passhrase.
        '''</summary>
        Friend ReadOnly Property enterbtcpassphrase() As String
            Get
                Return ResourceManager.GetString("enterbtcpassphrase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error sending transaction..
        '''</summary>
        Friend ReadOnly Property errorsendtx() As String
            Get
                Return ResourceManager.GetString("errorsendtx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception:.
        '''</summary>
        Friend ReadOnly Property exception() As String
            Get
                Return ResourceManager.GetString("exception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exeption thrown :.
        '''</summary>
        Friend ReadOnly Property exceptionthrown() As String
            Get
                Return ResourceManager.GetString("exceptionthrown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exiting....
        '''</summary>
        Friend ReadOnly Property exiting() As String
            Get
                Return ResourceManager.GetString("exiting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Build transaction failed.  Recipient address is not valid..
        '''</summary>
        Friend ReadOnly Property failedbuildtx() As String
            Get
                Return ResourceManager.GetString("failedbuildtx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to send transaction..
        '''</summary>
        Friend ReadOnly Property failedsendtx() As String
            Get
                Return ResourceManager.GetString("failedsendtx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transaction failed.
        '''</summary>
        Friend ReadOnly Property failedtx() As String
            Get
                Return ResourceManager.GetString("failedtx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Form1.
        '''</summary>
        Friend ReadOnly Property Form1() As String
            Get
                Return ResourceManager.GetString("Form1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Great, thanks.
        '''</summary>
        Friend ReadOnly Property greatthanks() As String
            Get
                Return ResourceManager.GetString("greatthanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property green_tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green-tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HIGH.
        '''</summary>
        Friend ReadOnly Property high() As String
            Get
                Return ResourceManager.GetString("high", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Highest Value.
        '''</summary>
        Friend ReadOnly Property highestvalue() As String
            Get
                Return ResourceManager.GetString("highestvalue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to historylist exception.
        '''</summary>
        Friend ReadOnly Property historylistexception() As String
            Get
                Return ResourceManager.GetString("historylistexception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property in1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("in1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insufficient Funds.
        '''</summary>
        Friend ReadOnly Property insufficientfunds() As String
            Get
                Return ResourceManager.GetString("insufficientfunds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invalid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invalid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recipient address is valid..
        '''</summary>
        Friend ReadOnly Property invalidrecipient() As String
            Get
                Return ResourceManager.GetString("invalidrecipient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AMOUNT:.
        '''</summary>
        Friend ReadOnly Property Label1() As String
            Get
                Return ResourceManager.GetString("Label1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TOTAL MASTERCOIN BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label10() As String
            Get
                Return ResourceManager.GetString("Label10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BTC BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label12() As String
            Get
                Return ResourceManager.GetString("Label12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RPC PASSWORD:.
        '''</summary>
        Friend ReadOnly Property Label13() As String
            Get
                Return ResourceManager.GetString("Label13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRMED BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label14() As String
            Get
                Return ResourceManager.GetString("Label14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNCONFIRMED BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label16() As String
            Get
                Return ResourceManager.GetString("Label16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DATE:.
        '''</summary>
        Friend ReadOnly Property Label17() As String
            Get
                Return ResourceManager.GetString("Label17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TO ADDRESS:.
        '''</summary>
        Friend ReadOnly Property Label18() As String
            Get
                Return ResourceManager.GetString("Label18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NETWORK STATUS:.
        '''</summary>
        Friend ReadOnly Property Label19() As String
            Get
                Return ResourceManager.GetString("Label19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FROM:.
        '''</summary>
        Friend ReadOnly Property Label2() As String
            Get
                Return ResourceManager.GetString("Label2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Key:.
        '''</summary>
        Friend ReadOnly Property Label20() As String
            Get
                Return ResourceManager.GetString("Label20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency.
        '''</summary>
        Friend ReadOnly Property Label22() As String
            Get
                Return ResourceManager.GetString("Label22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PORT.
        '''</summary>
        Friend ReadOnly Property Label23() As String
            Get
                Return ResourceManager.GetString("Label23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEST MSC BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label24() As String
            Get
                Return ResourceManager.GetString("Label24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADDRESS:.
        '''</summary>
        Friend ReadOnly Property Label25() As String
            Get
                Return ResourceManager.GetString("Label25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RECIPIENT ADDRESS:.
        '''</summary>
        Friend ReadOnly Property Label27() As String
            Get
                Return ResourceManager.GetString("Label27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SENDING ADDRESS:.
        '''</summary>
        Friend ReadOnly Property Label29() As String
            Get
                Return ResourceManager.GetString("Label29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currency.
        '''</summary>
        Friend ReadOnly Property Label3() As String
            Get
                Return ResourceManager.GetString("Label3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UNCONFIRMED BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label30() As String
            Get
                Return ResourceManager.GetString("Label30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CONFIRMED BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label31() As String
            Get
                Return ResourceManager.GetString("Label31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SORT BY:.
        '''</summary>
        Friend ReadOnly Property Label32() As String
            Get
                Return ResourceManager.GetString("Label32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PASSWORD:.
        '''</summary>
        Friend ReadOnly Property Label33() As String
            Get
                Return ResourceManager.GetString("Label33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MSC BALANCE:.
        '''</summary>
        Friend ReadOnly Property Label36() As String
            Get
                Return ResourceManager.GetString("Label36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SHOWING:.
        '''</summary>
        Friend ReadOnly Property Label37() As String
            Get
                Return ResourceManager.GetString("Label37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to RPC USER:.
        '''</summary>
        Friend ReadOnly Property Label39() As String
            Get
                Return ResourceManager.GetString("Label39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort By.
        '''</summary>
        Friend ReadOnly Property Label4() As String
            Get
                Return ResourceManager.GetString("Label4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BITCOIN RPC SERVER:.
        '''</summary>
        Friend ReadOnly Property Label40() As String
            Get
                Return ResourceManager.GetString("Label40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CURRENCY:.
        '''</summary>
        Friend ReadOnly Property Label42() As String
            Get
                Return ResourceManager.GetString("Label42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USER:.
        '''</summary>
        Friend ReadOnly Property Label43() As String
            Get
                Return ResourceManager.GetString("Label43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBUG LOG:.
        '''</summary>
        Friend ReadOnly Property Label44() As String
            Get
                Return ResourceManager.GetString("Label44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We&apos;ll need to configure a connection to your bitcoind/qt server.  Your bitcoind/qt server needs to have transaction indexing enabled to use this software.  Please enter the details below and click &apos;Test&apos; to test the connection to bitcoind/qt and confirm that the transaction index is enabled..
        '''</summary>
        Friend ReadOnly Property Label46() As String
            Get
                Return ResourceManager.GetString("Label46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SERVER:.
        '''</summary>
        Friend ReadOnly Property Label47() As String
            Get
                Return ResourceManager.GetString("Label47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GETTING STARTED:.
        '''</summary>
        Friend ReadOnly Property Label48() As String
            Get
                Return ResourceManager.GetString("Label48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Filter.
        '''</summary>
        Friend ReadOnly Property Label5() As String
            Get
                Return ResourceManager.GetString("Label5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You&apos;ll also need to choose a passphrase to encrypt the wallet database.  Note, your private keys are not stored in your Masterchest wallet database; transactions are signed using your bitcoin wallet..
        '''</summary>
        Friend ReadOnly Property Label50() As String
            Get
                Return ResourceManager.GetString("Label50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WALLET PASSPHRASE:.
        '''</summary>
        Friend ReadOnly Property Label51() As String
            Get
                Return ResourceManager.GetString("Label51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To speed up initial seeding, you can choose to use a preseeded database.  This will reduce the number of blocks to catchup, but requires that the preseeded database is trusted.
        '''</summary>
        Friend ReadOnly Property Label52() As String
            Get
                Return ResourceManager.GetString("Label52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only use this option if you downloaded this wallet from a trusted source.
        '''</summary>
        Friend ReadOnly Property Label53() As String
            Get
                Return ResourceManager.GetString("Label53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AMOUNT:.
        '''</summary>
        Friend ReadOnly Property Label54() As String
            Get
                Return ResourceManager.GetString("Label54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valid.
        '''</summary>
        Friend ReadOnly Property Label55() As String
            Get
                Return ResourceManager.GetString("Label55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid.
        '''</summary>
        Friend ReadOnly Property Label56() As String
            Get
                Return ResourceManager.GetString("Label56", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unconfirmed.
        '''</summary>
        Friend ReadOnly Property Label57() As String
            Get
                Return ResourceManager.GetString("Label57", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SORT BY:.
        '''</summary>
        Friend ReadOnly Property Label6() As String
            Get
                Return ResourceManager.GetString("Label6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PORT.
        '''</summary>
        Friend ReadOnly Property Label7() As String
            Get
                Return ResourceManager.GetString("Label7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBUG LEVEL:.
        '''</summary>
        Friend ReadOnly Property Label8() As String
            Get
                Return ResourceManager.GetString("Label8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FILTER:.
        '''</summary>
        Friend ReadOnly Property Label9() As String
            Get
                Return ResourceManager.GetString("Label9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Highest Balance.
        '''</summary>
        Friend ReadOnly Property LinkLabel4() As String
            Get
                Return ResourceManager.GetString("LinkLabel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All Currencies.
        '''</summary>
        Friend ReadOnly Property LinkLabel5() As String
            Get
                Return ResourceManager.GetString("LinkLabel5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Filter Active.
        '''</summary>
        Friend ReadOnly Property lnkaddfilter() As String
            Get
                Return ResourceManager.GetString("lnkaddfilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address Alpha.
        '''</summary>
        Friend ReadOnly Property lnkaddsort() As String
            Get
                Return ResourceManager.GetString("lnkaddsort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOW.
        '''</summary>
        Friend ReadOnly Property lnkdebug() As String
            Get
                Return ResourceManager.GetString("lnkdebug", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Filter Active.
        '''</summary>
        Friend ReadOnly Property lnkhistoryfilter() As String
            Get
                Return ResourceManager.GetString("lnkhistoryfilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recent First.
        '''</summary>
        Friend ReadOnly Property lnkhistorysort() As String
            Get
                Return ResourceManager.GetString("lnkhistorysort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Syncronized. .
        '''</summary>
        Friend ReadOnly Property loversync() As String
            Get
                Return ResourceManager.GetString("loversync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOW.
        '''</summary>
        Friend ReadOnly Property low() As String
            Get
                Return ResourceManager.GetString("low", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lowest Value.
        '''</summary>
        Friend ReadOnly Property lowestvalue() As String
            Get
                Return ResourceManager.GetString("lowestvalue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Powered by .
        '''</summary>
        Friend ReadOnly Property lpoweredby() As String
            Get
                Return ResourceManager.GetString("lpoweredby", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a sending address.
        '''</summary>
        Friend ReadOnly Property lsendavail() As String
            Get
                Return ResourceManager.GetString("lsendavail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait....
        '''</summary>
        Friend ReadOnly Property lwelstartup() As String
            Get
                Return ResourceManager.GetString("lwelstartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property maxicon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("maxicon3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MED.
        '''</summary>
        Friend ReadOnly Property med() As String
            Get
                Return ResourceManager.GetString("med", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception reading configuration :.
        '''</summary>
        Friend ReadOnly Property messageexception() As String
            Get
                Return ResourceManager.GetString("messageexception", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BITCOIN AUTO CONFIGURATION.
        '''</summary>
        Friend ReadOnly Property messageheader1() As String
            Get
                Return ResourceManager.GetString("messageheader1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-detection has determined your bitcoind/qt configuration does not have the RPC server enabled..
        '''</summary>
        Friend ReadOnly Property messageinfo1() As String
            Get
                Return ResourceManager.GetString("messageinfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-detection has determined your bitcoind/qt configuration does not have the transaction index enabled..
        '''</summary>
        Friend ReadOnly Property messageinfo2() As String
            Get
                Return ResourceManager.GetString("messageinfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sanity checking has detected addresses with multiple balance entries in the database.  It is not safe to continue.  The wallet will now exit..
        '''</summary>
        Friend ReadOnly Property messageinfo3() As String
            Get
                Return ResourceManager.GetString("messageinfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please add server=1 to bitcoin.conf and restart bitcoind/qt..
        '''</summary>
        Friend ReadOnly Property messagerequest1() As String
            Get
                Return ResourceManager.GetString("messagerequest1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please add txindex=1 to bitcoin.conf and restart bitcoind/qt with the -reindex flag to enable the transaction index..
        '''</summary>
        Friend ReadOnly Property messagerequest2() As String
            Get
                Return ResourceManager.GetString("messagerequest2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception testing connection to bitcoin via RPC :.
        '''</summary>
        Friend ReadOnly Property messagesstartexception1() As String
            Get
                Return ResourceManager.GetString("messagesstartexception1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was a problem configuring your connection to bitcoind/qt.  Both auto detection and manual configuration appear to have failed..
        '''</summary>
        Friend ReadOnly Property messagestartinfo1() As String
            Get
                Return ResourceManager.GetString("messagestartinfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to More please....
        '''</summary>
        Friend ReadOnly Property more() As String
            Get
                Return ResourceManager.GetString("more", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Filter Active.
        '''</summary>
        Friend ReadOnly Property nofilteractive() As String
            Get
                Return ResourceManager.GetString("nofilteractive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not configured..
        '''</summary>
        Friend ReadOnly Property notconfigured() As String
            Get
                Return ResourceManager.GetString("notconfigured", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Syncronized..
        '''</summary>
        Friend ReadOnly Property notsynchronized() As String
            Get
                Return ResourceManager.GetString("notsynchronized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property ok() As String
            Get
                Return ResourceManager.GetString("ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mastercoin Only.
        '''</summary>
        Friend ReadOnly Property onlymastercoin() As String
            Get
                Return ResourceManager.GetString("onlymastercoin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property out1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("out1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw transaction decode:.
        '''</summary>
        Friend ReadOnly Property rawtxdecode() As String
            Get
                Return ResourceManager.GetString("rawtxdecode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw transaction hex:.
        '''</summary>
        Friend ReadOnly Property rawtxhex() As String
            Get
                Return ResourceManager.GetString("rawtxhex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recent First.
        '''</summary>
        Friend ReadOnly Property recentfirst() As String
            Get
                Return ResourceManager.GetString("recentfirst", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redcross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redcross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test Mastercoin.
        '''</summary>
        Friend ReadOnly Property rsendtmsc() As String
            Get
                Return ResourceManager.GetString("rsendtmsc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select a sending address.
        '''</summary>
        Friend ReadOnly Property selectsendaddress() As String
            Get
                Return ResourceManager.GetString("selectsendaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to sign transaction.  Ensure wallet passphrase is correct..
        '''</summary>
        Friend ReadOnly Property signingfailed() As String
            Get
                Return ResourceManager.GetString("signingfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Signing appears successful..
        '''</summary>
        Friend ReadOnly Property signingsuccesstx() As String
            Get
                Return ResourceManager.GetString("signingsuccesstx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup ERROR: Connection to bitcoin RPC seems to be established but responses are not as expected.  Aborting startup..
        '''</summary>
        Friend ReadOnly Property starterror1() As String
            Get
                Return ResourceManager.GetString("starterror1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup ERROR: Exception testing connection to bitcoin via RPC. Aborting startup. E2:.
        '''</summary>
        Friend ReadOnly Property starterror2() As String
            Get
                Return ResourceManager.GetString("starterror2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup ERROR: Connection to database seems to be established but responses are not as expected.  Aborting startup..
        '''</summary>
        Friend ReadOnly Property starterror3() As String
            Get
                Return ResourceManager.GetString("starterror3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup ERROR: Enumerating addresses did not complete properly.  Aborting startup..
        '''</summary>
        Friend ReadOnly Property starterror4() As String
            Get
                Return ResourceManager.GetString("starterror4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Testing bitcoin connection....
        '''</summary>
        Friend ReadOnly Property startinfo1() As String
            Get
                Return ResourceManager.GetString("startinfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Connection to bitcoin via RPC established and sanity check OK..
        '''</summary>
        Friend ReadOnly Property startinfo2() As String
            Get
                Return ResourceManager.GetString("startinfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Testing database connection....
        '''</summary>
        Friend ReadOnly Property startinfo3() As String
            Get
                Return ResourceManager.GetString("startinfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Connection to database established and sanity check OK..
        '''</summary>
        Friend ReadOnly Property startinfo4() As String
            Get
                Return ResourceManager.GetString("startinfo4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Enumerating wallet addresses....
        '''</summary>
        Friend ReadOnly Property startinfo5() As String
            Get
                Return ResourceManager.GetString("startinfo5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Initializing....
        '''</summary>
        Friend ReadOnly Property startupinitializing() As String
            Get
                Return ResourceManager.GetString("startupinitializing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startup: Initialization Complete..
        '''</summary>
        Friend ReadOnly Property startupinitializingcomplete() As String
            Get
                Return ResourceManager.GetString("startupinitializingcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STATUS:.
        '''</summary>
        Friend ReadOnly Property status() As String
            Get
                Return ResourceManager.GetString("status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syncronized.  Last block scanned was block.
        '''</summary>
        Friend ReadOnly Property synchronizedlastblock() As String
            Get
                Return ResourceManager.GetString("synchronizedlastblock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Syncronizing....
        '''</summary>
        Friend ReadOnly Property synchronizing() As String
            Get
                Return ResourceManager.GetString("synchronizing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR: Connection to bitcoin RPC seems to be established but responses are not as expected..
        '''</summary>
        Friend ReadOnly Property testError1() As String
            Get
                Return ResourceManager.GetString("testError1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitcoin connection OK but transaction index appears disabled..
        '''</summary>
        Friend ReadOnly Property testInfo1() As String
            Get
                Return ResourceManager.GetString("testInfo1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitcoin connection OK and transaction index appears enabled..
        '''</summary>
        Friend ReadOnly Property testInfo2() As String
            Get
                Return ResourceManager.GetString("testInfo2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to connect to Bitcoin or could not locate seed wallet..
        '''</summary>
        Friend ReadOnly Property testInfo3() As String
            Get
                Return ResourceManager.GetString("testInfo3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TRANSACTION ID:.
        '''</summary>
        Friend ReadOnly Property transactionid() As String
            Get
                Return ResourceManager.GetString("transactionid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transaction not sent.
        '''</summary>
        Friend ReadOnly Property transactionnotsent() As String
            Get
                Return ResourceManager.GetString("transactionnotsent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to transaction sent.
        '''</summary>
        Friend ReadOnly Property transactionsent() As String
            Get
                Return ResourceManager.GetString("transactionsent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transaction sent, ID:.
        '''</summary>
        Friend ReadOnly Property transactionsentid() As String
            Get
                Return ResourceManager.GetString("transactionsentid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Thread exited..
        '''</summary>
        Friend ReadOnly Property txtdebugexit() As String
            Get
                Return ResourceManager.GetString("txtdebugexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uncof() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uncof", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property valid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("valid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recipient address is valid..
        '''</summary>
        Friend ReadOnly Property validrecipient() As String
            Get
                Return ResourceManager.GetString("validrecipient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Will now exit..
        '''</summary>
        Friend ReadOnly Property willnowexit() As String
            Get
                Return ResourceManager.GetString("willnowexit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found MSC transaction (simple send):.
        '''</summary>
        Friend ReadOnly Property workerblockscan1() As String
            Get
                Return ResourceManager.GetString("workerblockscan1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found MSC transaction (sell offer):.
        '''</summary>
        Friend ReadOnly Property workerblockscan2() As String
            Get
                Return ResourceManager.GetString("workerblockscan2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found MSC transaction (accept offer):.
        '''</summary>
        Friend ReadOnly Property workerblockscan3() As String
            Get
                Return ResourceManager.GetString("workerblockscan3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found MSC transaction (simple send):.
        '''</summary>
        Friend ReadOnly Property workerblockscan4() As String
            Get
                Return ResourceManager.GetString("workerblockscan4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Transaction processing starting....
        '''</summary>
        Friend ReadOnly Property workerblockscan5() As String
            Get
                Return ResourceManager.GetString("workerblockscan5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Finished, sleeping..
        '''</summary>
        Friend ReadOnly Property workerblockscan6() As String
            Get
                Return ResourceManager.GetString("workerblockscan6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found pending MSC transaction (simple send):.
        '''</summary>
        Friend ReadOnly Property workerblockscan7() As String
            Get
                Return ResourceManager.GetString("workerblockscan7", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to BLOCKSCAN: Found pending MSC transaction (sell offer):.
        '''</summary>
        Friend ReadOnly Property workerblockscan8() As String
            Get
                Return ResourceManager.GetString("workerblockscan8", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Thread &apos;workthread&apos; starting....
        '''</summary>
        Friend ReadOnly Property workerdebug1() As String
            Get
                Return ResourceManager.GetString("workerdebug1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Block Analysis for:.
        '''</summary>
        Friend ReadOnly Property workerdebug2() As String
            Get
                Return ResourceManager.GetString("workerdebug2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Block Analysis for pending transactions.
        '''</summary>
        Friend ReadOnly Property workerdebug3() As String
            Get
                Return ResourceManager.GetString("workerdebug3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Enumerating addresses....
        '''</summary>
        Friend ReadOnly Property workerdebug4() As String
            Get
                Return ResourceManager.GetString("workerdebug4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Sanity checking balances table...&quot;.
        '''</summary>
        Friend ReadOnly Property workerdebug5() As String
            Get
                Return ResourceManager.GetString("workerdebug5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: Thread exited with error condition..
        '''</summary>
        Friend ReadOnly Property workerdebug6() As String
            Get
                Return ResourceManager.GetString("workerdebug6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to DEBUG: SQL.
        '''</summary>
        Friend ReadOnly Property workerdebugSQL() As String
            Get
                Return ResourceManager.GetString("workerdebugSQL", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Connection to bitcoin RPC seems to be established but responses are not as expected..
        '''</summary>
        Friend ReadOnly Property workererror1() As String
            Get
                Return ResourceManager.GetString("workererror1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Connection to database seems to be established but responses are not as expected..
        '''</summary>
        Friend ReadOnly Property workererror2() As String
            Get
                Return ResourceManager.GetString("workererror2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Database block appears newer than bitcoinrpc blocks - is bitcoinrpc up to date? Exiting thread..
        '''</summary>
        Friend ReadOnly Property workererror3() As String
            Get
                Return ResourceManager.GetString("workererror3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Enumerating addresses did not complete properly..
        '''</summary>
        Friend ReadOnly Property workererror4() As String
            Get
                Return ResourceManager.GetString("workererror4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Connection to database threw an exception of:.
        '''</summary>
        Friend ReadOnly Property workererror5() As String
            Get
                Return ResourceManager.GetString("workererror5", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to ERROR: Blockchain scanning thread threw exception :.
        '''</summary>
        Friend ReadOnly Property workererror6() As String
            Get
                Return ResourceManager.GetString("workererror6", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to STATUS: Connection to bitcoin RPC established &amp; sanity check OK..
        '''</summary>
        Friend ReadOnly Property workerstatus1() As String
            Get
                Return ResourceManager.GetString("workerstatus1", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to STATUS: UI thread will remain but blockchain scanning thread will now exit..
        '''</summary>
        Friend ReadOnly Property workerstatus2() As String
            Get
                Return ResourceManager.GetString("workerstatus2", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to STATUS: Connection to database established &amp; sanity check OK..
        '''</summary>
        Friend ReadOnly Property workerstatus3() As String
            Get
                Return ResourceManager.GetString("workerstatus3", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to STATUS: Database starting at block.
        '''</summary>
        Friend ReadOnly Property workerstatus4() As String
            Get
                Return ResourceManager.GetString("workerstatus4", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to STATUS: Network is at block.
        '''</summary>
        Friend ReadOnly Property workerstatus5() As String
            Get
                Return ResourceManager.GetString("workerstatus5", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
